library(readxl)
epi_recipes <- read_excel("G:/AI/ML/Project Files/CookRecipe/epicurious-recipes-with-rating-and-nutrition/epi_recipes.xlsx")
View(epi_recipes)
nutrition_data <- epi_recipes[,c(1:6)]
View(nutrition_data)
summary(nutrition_data)
#Missing values present
boxplot(nutrition_data$calories, main = "Original Calories")
boxplot(nutrition_data$protein, main = "Original Protein")
boxplot(nutrition_data$fat, main = "Original Fat")
boxplot(nutrition_data$sodium, main = "Original Sodium")
#Calories and Sodium has extreme outliers - replacing with NA
cal_data <- boxplot.stats(nutrition_data$calories)
View(cal_data)
nutrition_data$calories <- replace(nutrition_data$calories,(nutrition_data$calories<cal_data$stats[1])|(nutrition_data$calories>cal_data$stats[5]),NA)
sod_data <- boxplot.stats(nutrition_data$sodium)
View(sod_data)
nutrition_data$sodium <- replace(nutrition_data$sodium,(nutrition_data$sodium<sod_data$stats[1])|(nutrition_data$sodium>sod_data$stats[5]),NA)
pro_data <- boxplot.stats(nutrition_data$protein)
View(pro_data)
nutrition_data$protein <- replace(nutrition_data$protein,(nutrition_data$protein<pro_data$stats[1])|(nutrition_data$protein>pro_data$stats[5]),NA)
fat_data <- boxplot.stats(nutrition_data$fat)
View(fat_data)
nutrition_data$fat <- replace(nutrition_data$fat,(nutrition_data$fat<fat_data$stats[1])|(nutrition_data$fat>fat_data$stats[5]),NA)
boxplot(nutrition_data$calories, main = "Calories - After removing outliers")
boxplot(nutrition_data$protein, main = "Protein - After removing outliers")
boxplot(nutrition_data$fat, main = "Fat - After removing outliers")
boxplot(nutrition_data$sodium, main = "Sodium - After removing outliers")
#Missing values in calories, protein, fat, sodium - replaced by average value.
avg_calories <- apply(nutrition_data[,c(3)], 2, mean, na.rm = TRUE)
avg_protein <- apply(nutrition_data[,c(4)], 2, mean, na.rm = TRUE)
avg_fat <- apply(nutrition_data[,c(5)], 2, mean, na.rm = TRUE)
avg_sodium <- apply(nutrition_data[,c(6)], 2, mean, na.rm = TRUE)
nutrition_data$calories <- replace(nutrition_data$calories,is.na(nutrition_data$calories),avg_calories)
nutrition_data$sodium <- replace(nutrition_data$sodium,is.na(nutrition_data$sodium),avg_sodium)
nutrition_data$protein <- replace(nutrition_data$protein,is.na(nutrition_data$protein),avg_protein)
nutrition_data$fat <- replace(nutrition_data$fat,is.na(nutrition_data$fat),avg_fat)
summary(nutrition_data)
